export const cardListString = `Inc,$$$,Name,$$$,Lv,$$$,Type,$$$,Cost,$$$,hasTrigger,$$$,Willpower,$$$,FX,$$$,NobaseLink,$$$,ImageLink,Color,$$$,Notes,$$$,Typeline,$$$,Set,$$$,Designer,$$$,Artist,$$$,DesArt,$$$,Prototype?,$$$,Type Sort Order
@@@,$$$,"Bert, Carnival Showman",$$$,1,$$$,Character - Bert,$$$,1rsrc&,$$$,,$$$,1 wp&,$$$,"grand~: Reveal a card from your hand and the top 3 cards of your deck. If any of them have matching names, +2wp& until end of turn.",$$$,tcgpics\joseph art\bert1.png,$$$,C:\nandeck(1)\tcgpics\joseph art\bert1.png,,$$$,,$$$,Lv.1 Character - Bert,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,D:Ananda Guneratne/A:Joseph Miller,$$$,,$$$,1
@@@,$$$,"Bert, Slick Salesman",$$$,2,$$$,Character - Bert,$$$,3rsrc&,$$$,,$$$,2 wp&,$$$,"grand~: Reveal up to three cards from your hand and gain 2 rsrc& for each different card type revealed. (The card types are character, event, support.)",$$$,tcgpics\joseph art\bert2.png,$$$,C:\nandeck(1)\tcgpics\joseph art\bert2.png,,$$$,,$$$,Lv.2 Character - Bert,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,D:Ananda Guneratne/A:Joseph Miller,$$$,,$$$,1
@@@,$$$,"Bert, Legendary Conman",$$$,3,$$$,Character - Bert,$$$,3rsrc&,$$$,,$$$,3 wp&,$$$,"For each card you reveal during a turn, gain 1 rsrc& (up to 8 rsrc&)",$$$,tcgpics\joseph art\bert3.png,$$$,C:\nandeck(1)\tcgpics\joseph art\bert3.png,,$$$,,$$$,Lv.3 Character - Bert,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,D:Ananda Guneratne/A:Joseph Miller,$$$,,$$$,1
@@@,$$$,"Doran, the Necrodude",$$$,1,$$$,Character - Doran,$$$,1rsrc&,$$$,,$$$,1 wp&,$$$,grand&: +2 wp& this turn if you have at least 5 cards in your discard.,$$$,tcgpics\prototype pixel art\necromancer.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\necromancer.png,,$$$,,$$$,Character - Doran,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,"Doran, Necro-Rising",$$$,2,$$$,Character - Doran,$$$,2rsrc&,$$$,,$$$,3 wp&,$$$,"grand&, 6 rsrc&: Discard an event to put 12 wp& on any quest Lv.2 or lower.",$$$,tcgpics\prototype pixel art\necromancer2.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\necromancer2.png,,$$$,,$$$,Character - Doran,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,"Doran, Necro-Skeletized",$$$,3,$$$,Character - Doran,$$$,3rsrc&,$$$,,$$$,5 wp&,$$$,"grand&, 8 rsrc&, exhaust: Distribute 13 wp& as you choose between any two quests Lv.3 or lower.",$$$,tcgpics\prototype pixel art\necromancer3.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\necromancer3.png,,$$$,,$$$,Character - Doran,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,"Dryad, the Dud",$$$,1,$$$,Character - Dryad,$$$,2rsrc&,$$$,,$$$,0 wp&,$$$,Exhaust: 2 rsrc&,$$$,tcgpics\prototype pixel art\dryad1.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\dryad1.png,,$$$,,$$$,Lv.1 Character - Dryad,$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,1
@@@,$$$,"Dryad, the Dude",$$$,2,$$$,Character - Dryad,$$$,4rsrc&,$$$,,$$$,1 wp&,$$$,Exhaust: 3 rsrc&,$$$,tcgpics\prototype pixel art\dryad2.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\dryad2.png,,$$$,,$$$,Lv.2 Character - Dryad,$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,1
@@@,$$$,"Dryad, the Oakencrest",$$$,3,$$$,Character - Dryad,$$$,7rsrc&,$$$,,$$$,2 wp&,$$$,Exhaust: 5 rsrc&,$$$,tcgpics\prototype pixel art\dryad3.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\dryad3.png,,$$$,,$$$,Lv.3 Character - Dryad,$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,1
@@@,$$$,"Eevin, Average Weatherman",$$$,1,$$$,Character - Eevin,$$$,2rsrc&,$$$,,$$$,1 wp&,$$$,grand~: You may put any number of cards from your hand on top of your deck. +1 wp& until end of turn for each card placed this way.,$$$,tcgpics\joseph art\eevin1.png,$$$,C:\nandeck(1)\tcgpics\joseph art\eevin1.png,,$$$,,$$$,Lv.1 Character - Eevin,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,D:Ananda Guneratne/A:Joseph Miller,$$$,,$$$,1
@@@,$$$,"Eevin, Honored Prophet",$$$,2,$$$,Character - Eevin,$$$,5rsrc&,$$$,,$$$,2 wp&,$$$,grand~: Reveal the top card of your deck. You may draw it or play it for free.,$$$,tcgpics\joseph art\eevin2.png,$$$,C:\nandeck(1)\tcgpics\joseph art\eevin2.png,,$$$,,$$$,Lv.2 Character - Eevin,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,D:Ananda Guneratne/A:Joseph Miller,$$$,,$$$,1
@@@,$$$,"Eevin, Oracle of Tomorrow",$$$,3,$$$,Character - Eevin,$$$,3rsrc&,$$$,trigger!,$$$,3 wp&,$$$,"You may look at the top card of your deck at any time.

trigger~, 0 rsrc&: Look at the top card of your deck, you may put it on the top or bottom. Put this card on the bottom of your deck, then you may check for trigger~ effects again.",$$$,tcgpics\joseph art\eevin3.png,$$$,C:\nandeck(1)\tcgpics\joseph art\eevin3.png,,$$$,,$$$,Lv.3 Character - Eevin,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,D:Ananda Guneratne/A:Joseph Miller,$$$,,$$$,1
@@@,$$$,"Finick, Phoenix",$$$,1,$$$,Character - Finick,$$$,2rsrc&,$$$,,$$$,1 wp&,$$$,"4 rsrc&: Search your deck for Finick, Phoenix Rising and put it into play. (Discard this card as normal)",$$$,tcgpics\prototype pixel art\finnick1.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\finnick1.png,,$$$,,$$$,Lv.1 Character - Finick,$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,1
@@@,$$$,"Finick, Phoenix Rising",$$$,2,$$$,Character - Finick,$$$,4rsrc&,$$$,,$$$,6 wp&,$$$,,$$$,tcgpics\prototype pixel art\finnick2.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\finnick2.png,,$$$,,$$$,Lv.2 Character - Finick,$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,1
@@@,$$$,"Jane, Hair-Dwelling Pixie",$$$,1,$$$,Character - Jane,$$$,3rsrc&,$$$,,$$$,1 wp&,$$$,grand&: Exhaust any number of supports to draw a card for each support exhausted.,$$$,tcgpics\joseph art\jane1.png,$$$,C:\nandeck(1)\tcgpics\joseph art\jane1.png,,$$$,,$$$,Lv.1 Character - Jane,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,Ananda Guneratne / Joseph Miller,$$$,,$$$,1
@@@,$$$,"Jane, Barber's Apprentice",$$$,2,$$$,Character - Jane,$$$,2rsrc&,$$$,,$$$,2 wp&,$$$,grand&: Ready a support.,$$$,tcgpics\joseph art\jane2.png,$$$,C:\nandeck(1)\tcgpics\joseph art\jane2.png,,$$$,,$$$,Lv.2 Character - Jane,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,Ananda Guneratne / Joseph Miller,$$$,,$$$,1
@@@,$$$,"Jane, Hairweaver",$$$,3,$$$,Character - Jane,$$$,3rsrc&,$$$,,$$$,3 wp&,$$$,"Your supports gain: ""Exhaust: Jane gets +1 wp& this turn""",$$$,tcgpics\joseph art\jane3.png,$$$,C:\nandeck(1)\tcgpics\joseph art\jane3.png,,$$$,,$$$,Lv.3 Character - Jane,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,Ananda Guneratne / Joseph Miller,$$$,,$$$,1
@@@,$$$,Lady of the Red Strings,$$$,1,$$$,Character - LotRS,$$$,3rsrc&,$$$,trigger!,$$$,3 wp&,$$$,grand~ or (trigger~ 2 rsrc~): Reveal cards from the top of your deck until you reveal a support or character that costs 3 rsrc~ or less. You may draw it or play it. Put the remaining cards on the bottom of your deck in the same order.,$$$,tcgpics\prototype pixel art\ladyRedStrings.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\ladyRedStrings.png,,$$$,,$$$,Lv.1 Character - LotRS,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,Octo-venturer,$$$,1,$$$,Character - Octo-venturer,$$$,2rsrc&,$$$,,$$$,2 wp&,$$$,grand&: 3 rsrc& and put 1 wp& on any quest.,$$$,tcgpics\prototype pixel art\octopus.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\octopus.png,,$$$,,$$$,Character - Octo,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,"Octo-venturer, Evolving",$$$,2,$$$,Character - Octo-venturer,$$$,3rsrc&,$$$,,$$$,4 wp&,$$$,"grand&, 5 rsrc&: Ready Octo-venturer and they gain +3wp& until end of turn.",$$$,tcgpics\prototype pixel art\octoEvolve.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\octoEvolve.png,,$$$,,$$$,Character - Octo,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,Pigimus the Loyal,$$$,2,$$$,Character - Pigimus,$$$,3rsrc&,$$$,,$$$,4 wp&,$$$,"grand~, 2 rsrc~: Look at the top 8 cards of your deck. You may draw a non-Pigimus character from among them. Put the rest on the bottom of your deck in any order.",$$$,tcgpics\prototype pixel art\pig02.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\pig02.png,,$$$,,$$$,Lv.2 Character - Pigimus,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,Pigimus,$$$,3,$$$,Character - Pigimus,$$$,3rsrc&,$$$,,$$$,3 wp&,$$$,"grand&, rsrc&: Draw two cards.",$$$,tcgpics\prototype pixel art\pig.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\pig.png,,$$$,,$$$,Character - Pig,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,"Pigimus Jr, the Armface Diplomat",$$$,1,$$$,Character - Pigimus Jr,$$$,3rsrc&,$$$,,$$$,3 wp&,$$$,Questing: +2 wp& if the next threshold of the quest has no costs other than wp& or rsrc&,$$$,tcgpics\prototype pixel art\pigJr01.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\pigJr01.png,,$$$,,$$$,Lv.1 Character - Pigimus Jr,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,"Robespierre, Radical Rhino",$$$,1,$$$,Character - Robspierre,$$$,4rsrc&,$$$,,$$$,4 wp&,$$$,"grand&: Both players draw 2 cards. Then, your opponent discards 2 cards.",$$$,tcgpics\joseph art\rob1.png,$$$,C:\nandeck(1)\tcgpics\joseph art\rob1.png,,$$$,,$$$,Lv.1 Character - Robspierre,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,Ananda Guneratne / Joseph Miller,$$$,,$$$,1
@@@,$$$,"Robespierre, Rhino Revolutionary",$$$,2,$$$,Character - Robspierre,$$$,3rsrc&,$$$,,$$$,6 wp&,$$$,"grand&: Discard any number of cards. For each card discarded, your opponent discards a card and this gets +2 wp& until end of turn.",$$$,tcgpics\joseph art\rob2.png,$$$,C:\nandeck(1)\tcgpics\joseph art\rob2.png,,$$$,,$$$,Lv.2 Character - Robspierre,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,Ananda Guneratne / Joseph Miller,$$$,,$$$,1
@@@,$$$,"Robespierre, Rotten Ruler",$$$,3,$$$,Character - Robspierre,$$$,0rsrc&,$$$,,$$$,3 wp&,$$$,"Whenever your opponent discards 2 or more cards from the same effect, gain 2 rsrc&",$$$,tcgpics\joseph art\rob3.png,$$$,C:\nandeck(1)\tcgpics\joseph art\rob3.png,,$$$,,$$$,Lv.3 Character - Robspierre,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,Ananda Guneratne / Joseph Miller,$$$,,$$$,1
@@@,$$$,"Sinch, Expert Swordswoman",$$$,1,$$$,Character - Sinch,$$$,3rsrc&,$$$,,$$$,3 wp&,$$$,"grand&: Each player discards a card and you may put 3 wp& on a quest. If your opponent did not discard a character, put 5 wp& on that quest instead.",$$$,tcgpics\prototype pixel art\sinch01.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\sinch01.png,,$$$,,$$$,Lv.1 Character - Sinch,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,"Sinch, Defier of God's Plans",$$$,2,$$$,Character - Sinch,$$$,4rsrc&,$$$,,$$$,4 wp&,$$$,grand&: Reveal your opponent's proph& and put 2 wp& on any quest. You may pay 3 rsrc& to discard that proph&,$$$,tcgpics\prototype pixel art\sinch02.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\sinch02.png,,$$$,,$$$,Lv.2 Character - Sinch,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,"Sinch, Who Doesn't Ever Forget",$$$,3,$$$,Character - Sinch,$$$,5rsrc&,$$$,,$$$,6 wp&,$$$,"grand&, 4 rsrc&: Put a support that costs 5 rsrc& or less from your discard into play exhausted.",$$$,tcgpics\prototype pixel art\sinch03.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\sinch03.png,,$$$,,$$$,Lv.3 Character - Sinch,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,Vol'Cahi,$$$,1,$$$,Character - Vol'Cahi,$$$,7rsrc&,$$$,,$$$,3 wp&,$$$,"On your opponent's turn, quests gain one level.",$$$,tcgpics\prototype pixel art\volCahi.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\volCahi.png,,$$$,,$$$,Lv.1 Character - Vol'Cahi,$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,1
@@@,$$$,"Vopi, the Batsquire",$$$,1,$$$,Character - Vopi,$$$,2rsrc&,$$$,,$$$,2wp&,$$$,"grand&, 2 rsrc&: Gain 5 rsrc&",$$$,tcgpics\prototype pixel art\bat.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\bat.png,,$$$,,$$$,Character - Vopi,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,"Vopi, Batknight",$$$,2,$$$,Character - Vopi,$$$,4rsrc&,$$$,,$$$,5 wp&,$$$,"grand&, 5 rsrc&: Draw a card and lower a quest's level by 2 until end of turn.",$$$,tcgpics\prototype pixel art\vopiKnight.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\vopiKnight.png,,$$$,,$$$,Character - Vopi,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,"Yetelu, Woad Knight",$$$,1,$$$,Character - Yetelu,$$$,3rsrc&,$$$,trigger!,$$$,2 wp&,$$$,grand& or (trigger& 2 rsrc&): Exhaust two opponent supports until their next prophecy phase.,$$$,tcgpics\prototype pixel art\treeKnight.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\treeKnight.png,,$$$,,$$$,Lv.1 Character - Yetelu,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,1
@@@,$$$,Acolyte of Assurance,$$$,1,$$$,Character (Acolyte),$$$,2rsrc&,$$$,,$$$,0 wp&,$$$,"grand~: Search your deck for another Acolyte character and put it into play.

+1 wp~ for each other Acolyte character you have in play.",$$$,tcgpics\prototype pixel art\aAssurance.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\aAssurance.png,,$$$,,$$$,Lv.1 Character (Acolyte),$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,1
@@@,$$$,Acolyte of Intrigue,$$$,1,$$$,Character (Acolyte),$$$,2rsrc&,$$$,,$$$,0 wp&,$$$,"grand~: Search your deck for another Acolyte character and put it into play.

+1 wp~ for each other Acolyte character you have in play.",$$$,tcgpics\prototype pixel art\aIntrigue.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\aIntrigue.png,,$$$,,$$$,Lv.1 Character (Acolyte),$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,1
@@@,$$$,Acolyte of Entertainment,$$$,1,$$$,Character (Acolyte),$$$,2rsrc&,$$$,,$$$,0 wp&,$$$,"grand~: Search your deck for another Acolyte character and put it into play.

+1 wp~ for each other Acolyte character you have in play.",$$$,tcgpics\prototype pixel art\aEntertainment.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\aEntertainment.png,,$$$,,$$$,Lv.1 Character (Acolyte),$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,1
@@@,$$$,Acolyte of Oration,$$$,1,$$$,Character (Acolyte),$$$,2rsrc&,$$$,,$$$,0 wp&,$$$,"grand~: Search your deck for another Acolyte character and put it into play.

+1 wp~ for each other Acolyte character you have in play.",$$$,tcgpics\prototype pixel art\aOration.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\aOration.png,,$$$,,$$$,Lv.1 Character (Acolyte),$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,1
@@@,$$$,Stone of Avarice,$$$,,$$$,Support,$$$,1rsrc&,$$$,,$$$,,$$$,,$$$,tcgpics\prototype pixel art\stoneOfAvarice.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\stoneOfAvarice.png,,$$$,,$$$,Support,$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,2
@@@,$$$,Doran's Unicorn Helper,$$$,,$$$,Support,$$$,2rsrc&,$$$,,$$$,,$$$,"Exhaust: +1 wp& to any character if you have two or fewer characters.
(Supports can be exhausted for 1 rsrc&)",$$$,tcgpics\prototype pixel art\\unicorn.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\\unicorn.png,,$$$,,$$$,Support,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,2
@@@,$$$,Boots of Beginnings,$$$,,$$$,Support,$$$,2rsrc&,$$$,,$$$,,$$$,Exhaust: +3 wp& to a character questing a quest where you have less than 8 wp& until end of turn.,$$$,tcgpics\cc0 icons\A_Shoes04.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\A_Shoes04.png,,$$$,,$$$,Support,$$$,Set 2,$$$,Ananda Guneratne,$$$,Ananda Guneratne,$$$,Ananda Guneratne,$$$,,$$$,2
@@@,$$$,Sword of Heroism,$$$,,$$$,Support,$$$,2rsrc&,$$$,,$$$,,$$$,Exhaust: +3 wp& to a character questing a quest where you have more than 16 wp& until end of turn.,$$$,tcgpics\cc0 icons\W_Gold_Sword.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\W_Gold_Sword.png,,$$$,,$$$,Support,$$$,Set 2,$$$,Ananda Guneratne,$$$,Ananda Guneratne,$$$,Ananda Guneratne,$$$,,$$$,2
@@@,$$$,Enchanted Bident,$$$,,$$$,Support,$$$,3rsrc&,$$$,,$$$,,$$$,"rsrc&, exhaust: Draw a card or +2wp& to any character. 
(Supports can be exhausted for 1 rsrc&)",$$$,tcgpics\prototype pixel art\bident.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\bident.png,,$$$,,$$$,Support,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,2
@@@,$$$,Historied Blade,$$$,,$$$,Support,$$$,3rsrc&,$$$,,$$$,,$$$,"Exhaust: +2 wp& to any character with at least 3 wp& until end of turn
(Supports can be exhausted for 1 rsrc&)",$$$,tcgpics\prototype pixel art\orangeSword.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\orangeSword.png,,$$$,,$$$,Support,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,2
@@@,$$$,Staff of Cowardice,$$$,,$$$,Support,$$$,3rsrc&,$$$,trigger!,$$$,,$$$,Discard from play or (trigger~ 1 rsrc~): Your opponent must pay 2 rsrc~ for each character that quests a quest Lv.1 or above until their next prophecy phase.,$$$,tcgpics\cc0 icons\W_Staff07.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\W_Staff07.png,,$$$,,$$$,Support,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,2
@@@,$$$,Mystic Seed,$$$,,$$$,Support,$$$,4rsrc&,$$$,,$$$,,$$$,Exhaust: Reveal the top card of your deck. You may draw it or play it for free. Destroy Mystic Seed.,$$$,tcgpics\cc0 icons\I_Clover.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\I_Clover.png,,$$$,,$$$,Support,$$$,Set 2,$$$,Ananda Guneratne,$$$,Ananda Guneratne,$$$,Ananda Guneratne,$$$,,$$$,2
@@@,$$$,Guillotine of Judgment,$$$,,$$$,Support,$$$,4rsrc&,$$$,trigger!,$$$,,$$$,"Whenever you discard a card you may ready this.

trigger&, 2 rsrc&: Your opponent must discard two cards.",$$$,tcgpics\joseph art\guillotine.png,$$$,C:\nandeck(1)\tcgpics\joseph art\guillotine.png,,$$$,,$$$,Support,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,D:Ananda Guneratne/A:Joseph Miller,$$$,,$$$,2
@@@,$$$,Edge of the Dauntless,$$$,,$$$,Support,$$$,5rsrc&,$$$,,$$$,,$$$,Discard from play: Gain 3 rsrc& and put 3 wp& on any quest.,$$$,tcgpics\prototype pixel art\dauntlessBlade.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\dauntlessBlade.png,,$$$,,$$$,,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,2
@@@,$$$,Cogwork Delvings,$$$,,$$$,Support,$$$,5rsrc&,$$$,,$$$,,$$$,Exhaust: Draw a card.,$$$,tcgpics\prototype pixel art\cogDelvings.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\cogDelvings.png,,$$$,,$$$,Support,$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,2
@@@,$$$,Staff of Greed,$$$,,$$$,Support,$$$,6rsrc&,$$$,,$$$,,$$$,"When Staff of Greed comes into play, pay 2 rsrc& or discard a support you control from play.

Exhausts for 3 rsrc&",$$$,tcgpics\prototype pixel art\greedStaff.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\greedStaff.png,,$$$,,$$$,Support,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,2
@@@,$$$,Combat Training,$$$,,$$$,Event,$$$,0rsrc&,$$$,trigger!,$$$,,$$$,"The active player must exhaust a character. If they did, they draw a card.",$$$,tcgpics\cc0 icons\E_Wood01.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\E_Wood01.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Krosan Fist of Solidarity,$$$,,$$$,Event,$$$,0rsrc&,$$$,trigger!,$$$,,$$$,Put 4 opponent wp& on a quest and gain 1 stars&,$$$,tcgpics\cc0 icons\S_Earth02.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\S_Earth02.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Borrow a Wizard's Hat,$$$,,$$$,Event,$$$,1rsrc&,$$$,,$$$,,$$$,Reduce the level of a quest by 1 until the end of the turn.,$$$,tcgpics\prototype pixel art\hat.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\hat.png,,$$$,,$$$,Event,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Assemble Amulet of Grim Protection,$$$,,$$$,Event,$$$,1rsrc&,$$$,,$$$,,$$$,+2 wp& to a character until and of turn and trigger& abilities this turn cost an additional card being discarded from their owner's hand.,$$$,tcgpics\cc0 icons\Ac_Necklace06.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\Ac_Necklace06.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Good shot!,$$$,,$$$,Event,$$$,2rsrc&,$$$,,$$$,,$$$,+4 wp& on a Lv.1 character of your choice until end of turn.,$$$,tcgpics\prototype pixel art\bow.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\bow.png,,$$$,,$$$,Event,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Doran's River Purification Spell,$$$,,$$$,Event,$$$,2rsrc&,$$$,,$$$,,$$$,You may discard a card to gain 2 stars&,$$$,tcgpics\cc0 icons\S_Water02.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\S_Water02.png,,$$$,,$$$,Event,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Doran's Conjured Help,$$$,,$$$,Event,$$$,2rsrc&,$$$,,$$$,,$$$,Put 3 wp& on any quest Lv.2 or lower.,$$$,tcgpics\prototype pixel art\helper.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\helper.png,,$$$,,$$$,Event,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Doran's Digging Technique,$$$,,$$$,Event,$$$,2rsrc&,$$$,,$$$,,$$$,Draw two cards.,$$$,tcgpics\prototype pixel art\shovel.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\shovel.png,,$$$,,$$$,Event,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Shadowdagger Lunge,$$$,,$$$,Event,$$$,2rsrc&,$$$,trigger!,$$$,,$$$,"Discard a card to add 5 wp& to a quest.

trigger&: Discard a card to remove 5 wp& from the current quest.",$$$,tcgpics\cc0 icons\W_Dagger019.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\W_Dagger019.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Farmer Appreciation Day,$$$,,$$$,Event,$$$,2rsrc&,$$$,trigger!,$$$,,$$$,The active player exhausts all their supports and gains 2 rsrc& for each support exhausted this way.,$$$,tcgpics\joseph art\farmer.png,$$$,C:\nandeck(1)\tcgpics\joseph art\farmer.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Ananda Guneratne,$$$,Joseph Miller,$$$,D:Ananda Guneratne/A:Joseph Miller,$$$,,$$$,3
@@@,$$$,Intimidation Tactics,$$$,,$$$,Event,$$$,3rsrc&,$$$,,$$$,,$$$,Remove 4 opponent wp& from a quest.,$$$,tcgpics\prototype pixel art\skull.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\skull.png,,$$$,,$$$,Event,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Swift Travel,$$$,,$$$,Event,$$$,3rsrc&,$$$,,$$$,,$$$,"Draw two cards and put 1wp& on a quest Lv.1 or lower.

If you control two or fewer characters, draw an additional card.",$$$,tcgpics\cc0 icons\S_Wind06.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\S_Wind06.png,,$$$,,$$$,Event,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Tense Exchange,$$$,,$$$,Event,$$$,3rsrc&,$$$,trigger!,$$$,,$$$,Draw a card and your opponent must discard a card.,$$$,tcgpics\cc0 icons\S_Bow08.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\S_Bow08.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Pie Break,$$$,,$$$,Event,$$$,3rsrc&,$$$,trigger!,$$$,,$$$,Exhaust an opponent's character until its owner's next prophecy phase.,$$$,tcgpics\cc0 icons\I_C_Pie.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\I_C_Pie.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Grave Tending By Torchlight,$$$,,$$$,Event,$$$,3rsrc&,$$$,,$$$,,$$$,"Gain 1 stars&. Whenever you would draw a card, you may draw this card from your discard pile instead.",$$$,tcgpics\prototype pixel art\grobTorch.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\grobTorch.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,3
@@@,$$$,Fateful Tsunami,$$$,,$$$,Event,$$$,4rsrc&,$$$,trigger!,$$$,,$$$,Each player exhausts all their supports until their next prophecy phase. Each player may play a support that costs 3 rsrc& or less exhausted.,$$$,tcgpics\cc0 icons\S_Water05.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\S_Water05.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Witch's Tale,$$$,,$$$,Event,$$$,4rsrc&,$$$,,$$$,,$$$,"proph&: You may choose not to discard this at the beginning of your prophecy phase. If you don't discard it, put a prophecy token on this card. If you do discard it, gain stars& equal to the number of prophecy tokens on it.",$$$,tcgpics\prototype pixel art\witchTale.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\witchTale.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Cole Hanton,$$$,Cole Hanton,$$$,Cole Hanton,$$$,,$$$,3
@@@,$$$,Consume Potion of Protection,$$$,,$$$,Event,$$$,6rsrc&,$$$,,$$$,,$$$,"Choose a quest, it will not cause trigger& abilities this turn. Ready two characters.",$$$,tcgpics\cc0 icons\P_Orange06.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\P_Orange06.png,,$$$,,$$$,Event,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,3
@@@,$$$,Doran's Goblin Diplomacy Mission,$$$,0,$$$,Quest,$$$,,$$$,,$$$,,$$$,"8 wp&: 1 stars&
16 wp&: 1 stars& or +3wp& here
24 wp&: 3 stars&",$$$,tcgpics\prototype pixel art\goblin.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\goblin.png,,$$$,,$$$,Lv.0 Quest,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,4
@@@,$$$,Gain the Trust of the Tusiki,$$$,0,$$$,Quest,$$$,,$$$,,$$$,,$$$,"5 wp&, proph& => Character: 1 stars&
10 wp&, boot&: 1 stars&
24 wp&, 2 rsrc&: 1 stars& and 4wp& on any other quest.",$$$,tcgpics\prototype pixel art\blueGoblin.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\blueGoblin.png,,$$$,,$$$,Lv.0 Quest,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,4
@@@,$$$,Royal Bodyguarding,$$$,1,$$$,Quest,$$$,,$$$,,$$$,,$$$,"5 wp&: 1 stars&
8 wp&: Draw a card, then discard a card boot~: +1wp~ here
25 wp~, exhaust two characters, discard two cards:  7 stars~, 4 rsrc~",$$$,"tcgpics\prototype pixel art\royalShield.png""",$$$,"C:\nandeck(1)\tcgpics\prototype pixel art\royalShield.png""",,$$$,,$$$,Lv.1 Quest,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,4
@@@,$$$,Crafting Ethereal Weapons,$$$,1,$$$,Quest,$$$,,$$$,,$$$,,$$$,"10 wp~: rsrc~
16 wp~, proph~=>Support: Draw a card.
30 wp~, proph~=>Support: 3 stars~, search your deck for a support and put it in your hand.",$$$,"tcgpics\prototype pixel art\hammer.png""",$$$,"C:\nandeck(1)\tcgpics\prototype pixel art\hammer.png""",,$$$,,$$$,Lv.1 Quest,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,4
@@@,$$$,Goblin Food Program,$$$,1,$$$,Quest,$$$,,$$$,,$$$,,$$$,"8 wp&: 1 stars&
16 wp&: 2 stars& or +4wp& here
24 wp&: 3 stars&",$$$,tcgpics\prototype pixel art\goblinFood.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\goblinFood.png,,$$$,,$$$,Lv.1 Quest,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,4
@@@,$$$,Forge the Relic,$$$,2,$$$,Quest,$$$,,$$$,,$$$,,$$$,"10wp~, exhaust a character: 1 stars~ and draw a card
20wp~, discard a card: 4 stars~ and 2 rsrc~
30 wp~, 8 rsrc~: 12 stars~",$$$,tcgpics\cc0 icons\Ac_Medal03.png,$$$,C:\nandeck(1)\tcgpics\cc0 icons\Ac_Medal03.png,,$$$,,$$$,Lv.2 Quest,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,4
@@@,$$$,Calming the Water Spirit,$$$,2,$$$,Quest,$$$,,$$$,,$$$,,$$$,"6wp&, 3rsrc&: Draw a card
12 wp&, 3rsrc&: 2 stars& and +9 wp& here boot&: 2 stars&
30wp&: 7 stars&",$$$,tcgpics\prototype pixel art\waterSpirit.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\waterSpirit.png,,$$$,,$$$,Lv.2 Quest,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,4
@@@,$$$,Goblin Shamanic Ritual,$$$,2,$$$,Quest,$$$,,$$$,,$$$,,$$$,"8 wp&: 2 stars&
16 wp&: 3 stars& or +5 wp& here
24 wp&: 3 stars&",$$$,tcgpics\prototype pixel art\goblinShaman.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\goblinShaman.png,,$$$,,$$$,Lv.2 Quest,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,4
@@@,$$$,The Bishop's Due,$$$,2,$$$,Quest,$$$,,$$$,,$$$,,$$$,"10wp~, rsrc~, discard a card: The next character you play this turn costs 4 rsrc~ less.
20wp~: Draw a card boot~: +3 wp~ here
30wp~, discard three cards: 7 stars~",$$$,tcgpics\prototype pixel art\bishopDue.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\bishopDue.png,,$$$,,$$$,Lv.2 Quest,$$$,Set 2,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,4
@@@,$$$,Fishing Errand,$$$,0,$$$,Quest - Neutral,$$$,,$$$,,$$$,,$$$,"4wp~, discard a card: 3 rsrc~
6wp~, discard a card: 1 stars~ book~
18wp~, discard two cards: 8 stars~",$$$,tcgpics\prototype pixel art\pole.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\pole.png,,$$$,,$$$,Lv.0 Quest - Neutral,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,5
@@@,$$$,Doran's Snail Mail Delivery,$$$,0,$$$,Quest - Neutral,$$$,,$$$,,$$$,,$$$,"2 wp~, discard your proph~: Draw two cards.
8 wp~, discard your proph~: 1 stars~ and draw two cards.
12 wp~, discard your proph~: 1 stars~ and 4rsrc~",$$$,tcgpics\prototype pixel art\snail.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\snail.png,,$$$,,$$$,Lv.0 Quest - Neutral,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,5
@@@,$$$,Doran's Treant Relocation,$$$,1,$$$,Quest - Neutral,$$$,,$$$,,$$$,,$$$,"8 wp~: Put 1 wp~ on another quest Lv.2 or lower
16 wp~: Put 1 wp~ on another quest Lv.2 or lower boot~: 1 stars~
24 wp~: 3 stars~",$$$,tcgpics\prototype pixel art\treant.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\treant.png,,$$$,,$$$,Lv.1 Quest - Neutral,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,5
@@@,$$$,Doran's Slime Hunting,$$$,1,$$$,Quest - Neutral,$$$,,$$$,,$$$,,$$$,"8 wp~: Draw two cards, then discard two cards.
16 wp~: 2 stars~ boot~: 1 stars~
30wp~: 1 stars~ and draw a card.",$$$,tcgpics\prototype pixel art\slime.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\slime.png,,$$$,,$$$,Lv.1 Quest - Neutral,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,5
@@@,$$$,Doran's Dragon Belligerence Reduction Program,$$$,2,$$$,Quest - Neutral,$$$,,$$$,,$$$,,$$$,"8 wp&: 2 stars&
16 wp&: 3 stars& book&
24 wp&: 5 stars&",$$$,tcgpics\prototype pixel art\drag.png,$$$,C:\nandeck(1)\tcgpics\prototype pixel art\drag.png,,$$$,,$$$,Lv.2 Quest - Neutral,$$$,Set 1,$$$,Joseph Miller,$$$,Joseph Miller,$$$,Joseph Miller,$$$,,$$$,5`;